Added GranularAccessScope request to AccessScopeService
nozzlegear/ShopifySharp pull request #912
Opened 2023-08-09 07:14 UTC by lucasabond

Following up on issue 840 https://github.com/nozzlegear/ShopifySharp/issues/840.

2023-08-12 07:04 UTC, nozzlegear requested changes

2023-08-12 07:04 UTC, nozzlegear commented on ShopifySharp/Services/AccessScope/AccessScopeService.cs
> +        public virtual async Task<IEnumerable<AccessScope>> RequestGranularAccessScopesAsync(IEnumerable<AuthorizationScope> requestedScopes, CancellationToken cancellationToken = default)
Looks good! Just need to add the two new methods to the service interface.

2023-08-12 07:04 UTC, nozzlegear commented on ShopifySharp/Services/AccessScope/AccessScopeService.cs
> +        public virtual async Task<IEnumerable<AccessScope>> RequestGranularAccessScopesAsync(IEnumerable<string> requestedScopes, CancellationToken cancellationToken = default)
Same here, this just needs to be added to the IAccessScopeService interface and we'll be good to go!

2023-08-12 07:05 UTC, nozzlegear commented
Awesome, thanks for the pull request! I just need one small change, can you please add the two new methods to the IAccessScopeService interface? Once that's done I'll get this merged and published.

2023-08-16 15:06 UTC, lucasabond commented
Just pushed the additions to the interface. Glad to be able to help. I think this is all I have for now, but will push any other additions I build out. Cheers.

2023-08-16 20:20 UTC, nozzlegear approved these changes

2023-08-16 20:20 UTC, merged